# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ls -la /usr/share/apache-maven-3.6.0/bin

#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    options: '-DskipTests'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    jdkArchitectureOption: 'x64'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    goals: 'install'
#
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'example-projects/example-project/pom.xml'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    jdkArchitectureOption: 'x64'
#    goals: 'package'
#
#- script: |
#    set -e
#    gradle analyze
#    java -jar ../../core/frontend-stubs-testing/target/antenna-test-project-asserter.jar ExampleTestProject build
#  workingDirectory: 'example-projects/example-project'
#  displayName: 'Gradle Test'
#
#- script: |
#    set -e
#    rm -R example-projects/example-project/target
#    .travis/runCLI.sh example-projects/example-project
#    java -jar core/frontend-stubs-testing/target/antenna-test-project-asserter.jar ExampleTestProject example-projects/example-project/target
#  displayName: 'CLI Test'